added all files
Macatuz/Macatuz-Microverse-Building-with-Backgrounds-and-Gradients pull request #1
Opened 2019-04-01 18:49 UTC by Macatuz

New Pull request n.n

2019-04-01 19:38 UTC, azdrenymeri requested changes
# Nice Work
### Design looks good
Here are some fixes you need to make 
- The name of the project is too long and unnecessary so don't include your name and the Microverse on the project name it should be simple.
- I see only one collaborator do you have a coding partner? 
- There is  only one commit make sure on your next project to commit more often(is suggested after every feature)
-  Update the README.md file, include a small description(explain the purpose of the project), the contributor's links and the live version if it is available.
- check https://validator.w3.org/#validate_by_input and fix the markup errors on your index.html file

2019-04-01 19:38 UTC, azdrenymeri commented on css/main.css
> +    text-align: center;
`text-align: center;` is also declared on line 30

2019-04-01 19:38 UTC, azdrenymeri commented on css/main.css
> +    font-size: 33px;
`font-size` property is overridden by line 32

2019-04-01 21:37 UTC, Macatuz commented
Gotcha! thanks am making the changes n.n.

2019-04-01 22:09 UTC, Macatuz commented
i wasnt able to add titles as first child of sections, as it will make the look diferent from the main site. so just let me know if i need to add them and i will.

2019-04-02 17:11 UTC, azdrenymeri commented
# Well Done 🥇 
### No more changes required from my side

2019-04-02 17:12 UTC, azdrenymeri commented
> Alright , Changes done! (I do have a partner but this project is individual)
> Indeed i wasn't able to add titles as first child of sections, as it will make the look different from the main site. so just let me know if i need to add them and i will.

No need

2019-04-02 17:19 UTC, merged